### ISSUE TITLE
Only the number of respondents set in 'cutoff rules' are contacted when survey is launched

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1005]
Version: 0.9.0 (build 2357)

Preconditions:
There is a questionnaire `Foo`

1. Create a survey for questionnaire `Foo`
2. Upload a respondent list of `10` respondents
3. Complete the rest of the survey configuration
3. In 'Cutoff rules' set `Number of completes: 3`
4. Launch survey

Obtained:
Only 3 respondents are contacted.

Expected:
All respondents are contacted, the survey ends when 3 of them complete the survey

**Comment by waj** [comment]
This is correct. According to https://github.com/instedd/ask/issues/939 and https://github.com/instedd/ask/issues/957 the number of contacted respondents depends on the success rates. Because we didn't setup any specific value for the initial success rates in the staging server the system asumes 100%.
