### ISSUE TITLE
Cases incorrectly classified as "Failed"

### ISSUE THREAD

**Issue by nditada** [instedd/ask#1073]
A test with Airtel was done here: https://surveda-zambia.org/projects/2/surveys/154

The only Airtel-generated codes in the Action Data in the Interactions file are: failed: User alerting, no answer (ISDN:19) and failed: Call Rejected (ISDN:21).
 
Since none of them are definitive problems based on ISDN definitions, the disposition should not be failed.

@mmuller @pmallol can you verify this? I haven't.

**Comment by mmuller** [comment]
@nditada yes, when the respondent rejects the phone call the disposition is failed.

**Comment by waj** [comment]
So, we are more afraid of false `failed` than false `contacted/unresponsive`? Right now the call is marked as `contacted` once we have the confirmation that the call was answered.

Even if we select which ISDN codes are definitive problems with the number, from my experience we cannot be ever 100% sure. For example, Callcentric would describe the error `ISDN:1 - Unallocated (unassigned) number` when the call is not answered. That would mark the call as failed instead of retrying.

**Comment by nditada** [comment]
@waj Yes, I understand, you have a good point.  We initially wanted to err on the side of retrying contacts unless we were positive the error was definitive. But if we have instances of ISDN:1 for answered calls it means we would never have any fails. I'll discuss with Charles.

**Comment by nditada** [comment]
@waj I have checked this on the phone with Charles and he confirmed we prefer to be "over-inclusive" with calling and err on the side of retrying contacts. If we can't trust the ISDN codes it means none of them should be coded as failed. Other more standard SIP errors could still generate a "failed" disposition code if we are positive the phone number will never work.

**Comment by nditada** [comment]
@waj based on our conversation, let's keep the change to "failed" disposition after all the contact attempt fail, regardless of the error code. There is no other disposition state that makes more sense in that situation. But let's keep the contact in "queued" while there are retries pending, regardless of the error as well.

**Comment by waj** [comment]
That's exactly how it works right now.
