### ISSUE TITLE
Bind 'enter' key to submit buttons and trigger a blur event in general

### ISSUE THREAD

**Issue by mverzilli** [instedd/ask#113]
1. When focus is on a form control and there's a submit button, 'enter' should be equivalent to clicking that button.

2. When focus there isn't a submit button, 'enter' should be equivalent to leaving the control or confirming the change (ie: blur).

Example of case 1: try to create a new project, enter a title, press enter. That should create the project, but it currently does nothing.

Example of case 2: the new "title widget" to edit the survey title.

**Comment by waj** [comment]
I agree but this is too general. The projects form doesn't exist anymore. Let's create separate issues when needed.

**Comment by asterite** [comment]
I tried to fix this once and it has to be seen case by case. For example in the questionnaire editor if you press enter and you fire the "save" action then the input you are editing doesn't take effect. This is because the "name changed" action is fired on blur, but the enter hit happens before the blur. One solution is to fire "changed" events on every keypress to avoid this issue.
