### ISSUE TITLE
Target Complete % is not working

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1424]
Reported by Adam: 

> For Pre-Test 5 (https://surveda-ph.org/projects/1/surveys/258), when we calculate the percent of the population reached, we get 79% by taking total completes/target = % complete (138/175) 

![image](https://user-images.githubusercontent.com/518152/43416420-913c42ae-940e-11e8-88e1-4fed42d6308b.png)

> The percent of target completed that is displayed on the “Surveys” screen does not do the same thing.   How does surveda calculate target completed?

![image](https://user-images.githubusercontent.com/518152/43416438-9cc7825a-940e-11e8-9f34-12416825b452.png)

**Comment by lmatayoshi** [comment]
The approach to compute the target completion depicted in the image is **OK**. 

Whenever quotas are present, the target is computed as the sum of the target in each quota and the current completion is computed in two different ways, depending on if the survey count partials as complete. If it does, it considers respondents whose disposition is in [completed, partial, interim partial]. If it doesn't, it should only consider respondents whose disposition is 'completed'.

The problem was that the computation was adding up 'partial' and 'interim partial' respondents to the current completion, despite of counting partial as complete being set to true or false. It should work properly now.

**Comment by mmuller** [comment]
Working properly in version 5ab25d2
