### ISSUE TITLE
The quantity totals are not right in survey dashboard when quotas are configured

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1425]
Reported by Adam Preston:
> It seems that if quotas are configured in the survey, then the totals (for Quantity)  in the survey dashboard aren't right.

![image](https://user-images.githubusercontent.com/518152/43416504-e1ef9fe8-940e-11e8-8f76-1770e839b7ac.png)
https://surveda-ph.org/projects/1/surveys/259

> When quotas aren't use, its fine.

https://surveda-ph.org/projects/1/surveys/250

**Comment by waj** [comment]
I suspect the problem here is that the "quantity" column counts all the respondents within that disposition, while the color columns only show respondents that has assigned a quota bucket already (the respondent might not answered yet the questions). @lmatayoshi please confirm

We have two options here:
1. Add another column to show the number of respondents still not assigned to a quota bucket
2. Subtract number of respondents without quota buckets from the "quantity" column

@nditada which option do we prefer?

**Comment by nditada** [comment]
I think option (1) is the most clear way for users.

**Comment by lmatayoshi** [comment]
The explanation above describes exactly what was happening: "Only the respondents with an assigned  quota bucket were being counted". Option (1) was implemented as the solution for this fix

**Comment by mmuller** [comment]
Column properly added in 5ab25d2
