### ISSUE TITLE
"Registered" disposition is not being logged in interactions/disposition files

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#1442]
Version: 0.20.0-dev-00fa649

Should "Registered" disposition state appear in the Interaction and Disposition files even when it's a state that can only result in "Queued" state once the respondent is set to be contacted automatically by the app?
[Disposition State chart](https://cloud.githubusercontent.com/assets/22697/25618659/3126839e-2f1e-11e7-8a3a-7908f8cd1749.png) as reference.

Preconditions:
The user already has a Project.
The Project already has a Questionnaire.
 
1. Create a survey
2. Select questionnaire, select channel, add respondents and set schedule
3. Start survey
4. Check that all respondents have state 'Registered' in Disposition chart in 'Overview' tab
5. Stop survey
6. Go to 'Respondents' tab
7. Download files: Results, Dispositions and Interactions

Results:
The state "Registered" only appears in the Results file.

**Comment by pmallol** [comment]
Related to #1413

**Comment by lmatayoshi** [comment]
For now, we will not add _Registered_ rows to _Interactions_ and _Disposition History_ files mainly because of these 2 reasons:

- It doesn't provide any valuable information
- In order to be implemented correctly, entries associated with the _Registered disposition_ should be added during the respondent group creation (i.e during the upload of the respondents file), thus considerably increasing the amount of time required for the upload

**Comment by pmallol** [comment]
Thank you very much @lmatayoshi!
