### ISSUE TITLE
[Survey] New survey should use the local timezone

### ISSUE THREAD

**Issue by waj** [instedd/ask#304]
When creating a new survey, try to use the local timezone of the user browser

**Comment by asterite** [comment]
I implemented this by using [Intl.DateTimeFormat().resolvedOptions().timeZone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_compatibility), but not all browsers support it. It works on Chrome and seems to give the correct timezone. On Firefox it doesn't work. There are some libraries, like [jstz](http://pellepim.bitbucket.org/jstz/) and [moment-timezone](http://momentjs.com/timezone/), but they try to guess the timezone, not use the one from the OS, and they give a result like "America/Argentina/Buenos_Aires" in Firefox, where the correct one should be "America/Buenos_Aires", so that won't work unless we change the library or do some conversions.

**Comment by pmallol** [comment]
Ok in Version: 0.4.0-dev-8ab670d (build 801)
