### ISSUE TITLE
Choose Material library

### ISSUE THREAD

**Issue by nditada** [instedd/ask#32]
http://materializecss.com/media-css.html

or 

http://www.material-ui.com/

@ggiraldez any opinions?

**Comment by ggiraldez** [comment]
I'd go for Material UI since it's specifically designed for React.

materializecss has two drawbacks IMHO: uses jQuery and forces you to annotate your components with CSS classes. Integration with React is not as straightforward and you might have other issues, depending on what it does with jQuery.

Having said that, I haven't used either and I don't know how well designed and reliable is Material UI.

**Comment by waj** [comment]
Closed with 87d4b81 (using materialize-css)

Even though Material UI was specifically targeted for React, it was not flexible enough in some aspects. Making React components from already defined components in materialize-css is quite easy anyway, and it also provides a built in responsive grid layout.
