### ISSUE TITLE
Download responses as CSV

### ISSUE THREAD

**Issue by waj** [instedd/ask#325]
Add a download button in the respondents page to obtain a CSV with all the results

https://projects.invisionapp.com/d/main#/console/8374235/186815708/preview

**Comment by asterite** [comment]
@waj Should the phone numbers be masked in the CSV too?

**Comment by edjez** [comment]
For the moment, yes. But make sure there is a repeatable unique id for each
one, hence the early mentions of "hashes" and not "masks"


On Nov 21, 2016, at 08:08, Ary Borenszweig <notifications@github.com> wrote:

@waj <https://github.com/waj> Should the phone numbers be masked in the CSV
too?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/instedd/ask/issues/325#issuecomment-261981702>, or mute
the thread

**Comment by waj** [comment]
If we have to hash the phone numbers, we need to choose a hash algorithm. This algorithm could be computationally easy or hard:

  * easy: because we're hashing just phone numbers it's really easy to guess the original phone number given the hash

  * hard: it would take just too much time to hash all the phone numbers either at the moment of the csv export or when the respondents are imported into the database

Can't we just use a randomly generated ID for each respondent? What's the purpose of having a repeatable id? Aren't the surveys meant to be as anonymous as possible?
