### ISSUE TITLE
Setup cutoff rules never gets highlighted

### ISSUE THREAD

**Issue by pmallol** [instedd/ask#332]
Version: 0.4.0-dev-8ab670d (build 801)

1. Open a project
2. Create a survey
3. Click on 'Setup cutoff rules'

Obtained:
All links get highlighted in grey when clicked but 'Setup cutoff rules' link

![screen shot 2016-11-21 at 4 50 53 pm](https://cloud.githubusercontent.com/assets/9214460/20498249/2a911f7c-b00b-11e6-9a6c-d6068b9f4972.png)

**Comment by juanboca** [comment]
This is because since the step has a low height, Scrollspy (http://materializecss.com/scrollspy.html) doesn't detect the last step as the active one. 
In lower resolutions than 1440x900 (Mac default), works fine. 
The cutoff step should have a min-height (500px works fine for the cited resolution), or an empty separator should be added for the highlight to work.
