### ISSUE TITLE
[Survey] Uploading respondents list after setting quotas yields a server error

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#407]
- Create a new survey
- Choose a questionnaire
- Turn on quotas for completes, choosing a variable
- Upload a respondents CSV

A server error is thrown.

Note that unchecking Quotas for completes allows for the respondents CSV to be uploaded without issues.

Seems to be https://sentry.io/instedd/ask/issues/191221539/

```
Elixir.Ecto.StaleEntryErrorEcto.Repo.Schema.apply/4
errorattempted to delete a stale struct: %Ask.QuotaBucket{__meta__: #Ecto.Schema.Metadata<:loaded, "quota_buckets">, condition: %{"smokes" => "No"}, count: 0, id: 157, inserted_at: #Ecto.DateTime<2016-12-07 17:01:06>, quota: nil, survey: #Ecto.Association.NotLoaded<association :survey is not loaded>, survey_id: 412, updated_at: #Ecto.DateTime<2016-12-07 17:01:06>}
```

**Comment by nekron** [comment]
The respondents upload and delete is triggering a duplicated survey save, which in turn is trying to delete and regenerate the buckets in the database. When running in staging this will load the surveys and buckets in parallel, and then one of those requests will try to delete a bucket that has been already deleted.

The event is being triggered at react level, because two SURVEY_SAVING and SURVEY_SAVED events are being dispatched.

The issue cannot be reproduced in development, because the server is running in a single thread, and the save is reaching the database sequentially.

Removing the duplicated save event should fix this bug.
