### ISSUE TITLE
[Questionnaire] Selecting "next question" as skip logic generates invalid flow

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#414]
- Create a questionnaire with several multiple choice questions
- Set up ranges with skip logic in one of the questions
- In one of the options, change from _next question_ to _end survey_
- Wait for the questionnaire to be saved (might not be necessary)
- Change back from _end survey_ to _next question_

The resulting internal representation has `skip_logic: ""` (that is, empty string) instead of `skip_logic: null`. When the broker needs to resolve `skip_logic: ""`, it fails with an error `Skip logic: invalid step id` and crashes.

**Comment by asterite** [comment]
Is there anything to do here? There's a label "solved-on-bugbash" on this issue

**Comment by juanboca** [comment]
The label is to remember that it was solved on the bugbash, and the solution should be checked. Also the commit says that it is a provisional fix.

To solve this, the exception that was raised (and commented on the commit) should be uncommented and catched on the broker, so the respondent can be marked as errored, and the error can be logged properly, instead of killing the broker process.

**Comment by mverzilli** [comment]
Agree on managing the exception, but I'll also fix the client so it sends skip_logic: null as expected and beef up the JSON schema so that it doesn't allow empty strings, so we don't cause this to ourselves unnecessarily :)
