### ISSUE TITLE
Removing a channel crashes the broker

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#549]
Steps:

- Create and start a survey
- While the survey is running, delete the channel it is running on (either on Verboice or Nuntium) and refresh the channels in Ask

The broker will crash with the following error, and no calls will be made or sms be sent. 
```
15:47:04.200 [error] GenServer Ask.Runtime.Broker terminating
** (UndefinedFunctionError) function nil.provider/0 is undefined (module nil is not available)
    nil.provider()
    (ask) Ask.Channel.runtime_channel/1
    (ask) lib/ask/runtime/session.ex:51: Ask.Runtime.Session.timeout/1
    (ask) lib/ask/runtime/broker.ex:118: Ask.Runtime.Broker.retry_respondent/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (ask) lib/ask/runtime/broker.ex:37: Ask.Runtime.Broker.handle_info/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
```
The only way to fix this situation is to manually delete the survey from the DB, since it is not possible to delete a survey or modify it to use a different channel.

**Comment by nekron** [comment]
Check if that's still happening

**Comment by asterite** [comment]
Either deleting a channel in Nuntium/Verboice or in Surveda while a survey is running doesn't crash the broker anymore. However, there's no indication that there's something wrong going on with the survey.

**Comment by waj** [comment]
When the channel doesn't exist let's raise a SurveyFatalError. The broker must handle those errors and stop the survey.

**Comment by asterite** [comment]
I can't trigger this anymore because in order to delete a channel you need to delete the related respondent groups (there's a foreign key for that) and apparently when you delete a respondent group all its respondents are deleted (I couldn't find where in the code, though, but that's what happens). So there's no way to reproduce this error anymore. I'll leave it open in case someone else wants to tackle it and finds a way to reproduce it.
