### ISSUE TITLE
Explanation Step - Delivered out of order

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#666]
What happened: 
- I was testing some SMS questionnaires that use an explanation step.  
- For one of the set of steps the messages came out of sequence.  

Question: 
- Is there anything else we can do to optimize the likelihood that messages will be delivered in their anticipated order?
- Is there any assumptions we can make about the liklihood of this happening?

**Comment by mmuller** [comment]
@steesdale I couldn't reproduce this issue.

Tested in version ee7b498.

Screenshots:
<img width="1421" alt="screen shot 2017-02-17 at 10 09 59 am" src="https://cloud.githubusercontent.com/assets/518152/23066419/46e348d4-f4f9-11e6-9dfd-bc3733b00980.png">

<img width="293" alt="screen shot 2017-02-17 at 10 10 18 am" src="https://cloud.githubusercontent.com/assets/518152/23066423/51b2c41a-f4f9-11e6-96d8-8250b801eb9f.png">

**Comment by waj** [comment]
@steesdale What channel are you using to send the messages? The system sends all the messages in order but one right after the other in really short time. They can arrive in a different order because  it's actually almost impossible to guarantee SMS delivery in the same order (https://support.twilio.com/hc/en-us/articles/223134247-Can-my-SMS-messages-arrive-in-order-). Maybe we should send the messages with a short delay in between.

**Comment by steesdale** [comment]
I was using a twilio channel for SMS.  I noted that many times it presented correctly.  But 1 time it did not.   

That said, I would be curious for us to find a way to test this and confirm the frequency, also I dont know if it is MNO specific, and if there is anything we should do to improve the probability. 

Lastly, in the design of the survey they are planning to use [1/2] & [2/2] style denotations in the question prompt to control for this challenge as well.

**Comment by steesdale** [comment]
im going to close this one for now.  Its duplicative of https://github.com/instedd/ask/issues/753
