### ISSUE TITLE
[Survey] When cancelling a Survey an error is thrown.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#736]
Found in version: 02bcf64

Preconditions:
There is a Survey running.
The Survey uses the voice mode to send the questions.

Reproduce steps:
Don't answer the phone. The call is marked as failed in Verboice.
Click on the Stop  button in order to cancel the Survey.

Obtained:
The following error is displayed: `Something went wrong`.
https://sentry.io/instedd/ask-stg/issues/169759417/

**Comment by asterite** [comment]
This happens because when the call failed the survey is marked as completed (I'm assuming there's only one respondent here). The UI is still showing the "cancel" button, so when you hit "cancel" you get an error because the survey can't be cancelled anymore, because it's completed.

I fixed this by simply not giving an error and redirecting to the survey status page again. It will show "completed" instead of "cancelled", because that's what really happened in the background. Maybe in the future we could add a message like "You tried to cancel a survey that was already completed" but it's very low priority in my opinion.

**Comment by mmuller** [comment]
Working properly in version 5c13734
