### ISSUE TITLE
Audio files and multiple languages

### ISSUE THREAD

**Issue by adam704a** [instedd/ask#746]
Audio files uploaded into questions in the questionnaire designer with multiple languages will use the same audio file across all languages.

Example: http://ask-demo.instedd.org/projects/52/questionnaires/99/edit

The language selection step has a French audio file uploaded, but that audio file is used for English and French.

This is happening in Fir.

**Comment by spalladino** [comment]
Hey Adam! The language selection step is the only step that will share the same resource across all languages. It is expected to have a single text or recording that covers all languages, such as "Press one for English, presione 2 para Español". What you are describing is expected behaviour for that step. 

Now, if you have stumbled upon this in _any other_ kind of step, let us know as it is definitely a bug. Also, we'll make a note to ensure that this resource is shared across all languages.

**Comment by spalladino** [comment]
Closing for now. Please reopen if you encounter this problem in other steps.
