### ISSUE TITLE
Show upload progress for CSV respondent files

### ISSUE THREAD

**Issue by spalladino** [instedd/ask#793]

**Comment by spalladino** [comment]
@jkicillof any hints on how to show an upload in progress here?

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/8374235/206251445/preview

**Comment by asterite** [comment]
@spalladino I assume the upload progress will be relative to the upload of the CSV file itself, right? I ask because most of the time will be consumed on the server side and will be much slower than the actual upload, and in that case there's no (easy) way to show a progress indication. So will the upload progress be enough?

@jkicillof I think we need a progress bar, not a spinning wheel (I might be wrong)

**Comment by spalladino** [comment]
Let's use a spinning wheel, displaying an "Uploading X%..." legend, that switches to a "Processing..." when the upload is complete and the server is creating the respondents. Does that sound ok?

**Comment by asterite** [comment]
I finally implemented this by showing just "Uploading...". From a user perspective "Uploading" and "Processing" doesn't give much information, in any case she'll have to wait until both finish. And the implementation is easier.

**Comment by mmuller** [comment]
Working properly in version 9c248ee
