### ISSUE TITLE
Update survey mode selection to avoid having 9 radio buttons

### ISSUE THREAD

**Issue by nekron** [instedd/ask#861]
Apply a design according to:
https://projects.invisionapp.com/d/main#/console/8374235/231944357/preview and 
https://projects.invisionapp.com/d/main#/console/8374235/231944358/preview

Remove the headers and build the last combo with the phrase inlined like:

> `SMS` with `Phone call` fallback `+`

Clicking the `+` accepts that option and adds a row to the selected modes. That row will have a description of the selected modes, like we have now, and a bin icon on the right to remove it.

The combos at the bottom will update to only display the available modes.

If only one mode is available, but multiple fallbacks, or vice versa, remove the combo and display the mode or fallback as in one of the already accepted rows.

When no more modes nor fallbacks are available, don't display the bottom line.

**Comment by lmatayoshi** [comment]
How should different parts of the mode selection be aligned? Selectors seem to be aligned to the checkbox. Are selected options correctly aligned?

Is it OK the 'Add mode button'? How should it be displayed when disabled?

<img width="1439" alt="survey-modes-wizard" src="https://cloud.githubusercontent.com/assets/8591752/25601049/6ebc26be-2ebf-11e7-88d2-2e1c6d26f689.png">

Are options in read-only mode correctly displayed?

<img width="1440" alt="survey-modes-read-only" src="https://cloud.githubusercontent.com/assets/8591752/25601082/bd51b80c-2ebf-11e7-83ec-12f0bf8e926e.png">

**Comment by lmatayoshi** [comment]
@Mscebba: Apply style for the mode selection according to the Invision mockups that appears in the description above. You have to work in branch _feature/861-update-survey-mode-selection_.

By the moment, this is the current style for the mode selection:

Single mode:
![modes-single](https://cloud.githubusercontent.com/assets/8591752/25669655/82073848-3000-11e7-950f-fb849c15276b.png)

Comparison mode:
![modes-comparison](https://cloud.githubusercontent.com/assets/8591752/25669676/956c45fe-3000-11e7-8bdd-be12e00fff6d.png)

Things that must be done:
- [ ] (Comparison) Delete buttons for each selected mode should be aligned to the **+** button
- [ ] **+** button should be blue, instead of black. When is disabled, it should be grey. Colors used to be correct, but the style applied in the table seems to be blocking it
- [ ] General layout of the whole table should be corrected (height and width for each row, headers, grey hover, etc)

**Comment by mmuller** [comment]
Working properly in version a74ed81
