### ISSUE TITLE
[Mobile Web] Language selection step displayed incorrectly

### ISSUE THREAD

**Issue by waj** [instedd/ask#877]
<img width="325" alt="screen shot 2017-04-18 at 2 26 06 pm" src="https://cloud.githubusercontent.com/assets/22697/25144202/642ddf48-2443-11e7-91ea-9e1c0b01692b.png">

Let's remove the extra empty option, and display language names instead of codes.

**Comment by asterite** [comment]
This happens because we add an extra option to the language selection step so that indexing with the user choice (1, 2, etc.) directly indexes the item. This "invisible" option in SMS and IVR is now showing in mobile web.

To solve it, either hide the first option, or considering not adding that extra option in the first place (though that involves a migration to remove it from existing questionnaires)

**Comment by asterite** [comment]
I fixed this by assuming the dummy `nil` first choice is still there. I opened #894 to fix the hack, which now has less priority because it now works well.

**Comment by mmuller** [comment]
Working properly in version bb5bb2e
