### ISSUE TITLE
[Mobile Web] Language selection step doesn't work

### ISSUE THREAD

**Issue by waj** [instedd/ask#880]
Clicking on any language option always replies with "invalid response" message

**Comment by asterite** [comment]
There's also a bug that shows an extra empty option. This happens because we add an extra option to the language selection step so that indexing with the user choice (1, 2, etc.) directly indexes the item. This "invisible" option in SMS and IVR is now showing in mobile web.

To solve the first bug (the "invalid response"), send 1, 2, etc., instead of "en", "es".

To solve the second bug, either hide the first option, or considering not adding that extra option (though that involves a migration to remove it from existing questionnaires)

**Comment by asterite** [comment]
I fixed this by assuming the dummy `nil` first choice is still there. I opened #894 to fix the hack, which now has less priority because it now works well.

**Comment by mmuller** [comment]
Working properly in version bb5bb2e
