### ISSUE TITLE
Mobile Web Survey App Title is Odd

### ISSUE THREAD

**Issue by edjez** [instedd/ask#903]
Currently "InSTEDD Surveda"
Survey-taking link should have an html title like "Your survey" - or the SMS Intro text (/"Mobile Web SMS message")

![image](https://cloud.githubusercontent.com/assets/1182549/25203911/fe7ce89c-250f-11e7-8c5a-0fdbf1d90359.png)

**Comment by waj** [comment]
Let's use the "Title" field set in the questionnaire settings

**Comment by asterite** [comment]
There's a tiny problem: the "Title" field is editable via draft-js, and because it's a field of a mobile web setting it can have html tags, bold, etc. We can either:

1. Make the title field plain text
2. Strip HTML tags from the title to show it as as a title

The "title" field is currently being used in the header of a questionnaire in the mobile web mode. I guess nobody will want to use bold or italics there, but I'm not sure.

What should we do?

**Comment by nditada** [comment]
Let's do 1, it makes no sense to allow formatting on the Title.

**Comment by mmuller** [comment]
Working properly in version 73cc296
