### ISSUE TITLE
[Questionnaire] The Import Questionnaire link can be pressed several times until the popup is displayed.

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#908]
Found in version aebfaec

Preconditions:
There is a zip file `123`.
`123` contains the Questionnaire `123`.

Reproduce steps:
Create a Questionnaire.
Press the `Import Questionnaire` button several times.
Select the file `123`.
Observe the popup to select a file is displayed again.
Select the file `123`.

Obtained:
For each time that the `Import questionnaire` button is pressed the file selection popup is displayed.
The popup to select a file is displayed after selecting a file.
The upload process spends a lot of time and throws an error.

Expected:
The file selection popup should not be displayed again if a file was already selected.
If the button was pressed and the popup is not displayed the button should be disabled.

http://recordit.co/FYUB5hF3WL

**Comment by asterite** [comment]
(the recordit link doesn't exist anymore)

**Comment by mmuller** [comment]
@asterite here a new recordit link: http://recordit.co/VqbJUqse7o

**Comment by mmuller** [comment]
@asterite here a new recordit link: http://recordit.co/7YQ7FUe35B

**Comment by waj** [comment]
The link must be disabled until the popup is cancelled or the import finishes to avoid handling "double clicks"

**Comment by asterite** [comment]
It seems it's a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=638874&q=component%3ABlink%3EForms%3EFile%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) (see also [this](http://stackoverflow.com/questions/39772671/file-input-dialog-opening-very-slowly-in-google-chrome)). It happens because the "Import questionnaire" has a hidden `<input type="file"` with an `accept=".zip"` attribute. Chrome has a delay when it has to find zip files, apparently (it happens with other files too). It doesn't happen with CSV files, that's why this bug doesn't reproduce when you click on "Upload contents as CSV".

Additionally, there's no even fired when a user clicks "Cancel" on the file input dialog, so there's really no way to know when it was closed. There are some hacks in stack overflow (like listening to the focus event on the whole page) but I wouldn't use them.

One workaround is to remove the `accept` attribute, but then any file will be selectable in the dialog.

I'd say to move this to "minor": the app doesn't break if you click multiple times on the import, the dialog just opens up again. But if anyone wants to tackle this, be prepared for a lot of "fun" ;-)

**Comment by asterite** [comment]
Some with exactly the same issue: http://stackoverflow.com/questions/42619592/accept-key-word-in-input-type-file-accept-zip-opens-file-manager-multip . Unfortunately no solution yet :-(

**Comment by asterite** [comment]
I created a PR with a workaround for this issue: https://github.com/instedd/ask/pull/935

**Comment by mmuller** [comment]
Working properly in version dafd799
