### ISSUE TITLE
[Respondent] Speed of Questionnaire is Slow

### ISSUE THREAD

**Issue by steesdale** [instedd/ask#961]
The lag between questions feels really long.  Likely will drive down participation rates.

What can we do to move the questionnaire along quicker. 

Here is an example questionnaire with this issue: http://ask.instedd.org/projects/125/questionnaires/174/edit

Specifically, is it the audio files being used need to be trimmed to remove dead time?   Is it the lag between questions?   Is it the tool waiting for a response?   Some thing else?

**Comment by waj** [comment]
We can improve this by forcing Verboice to accept only one digit response in multiple choice steps

**Comment by asterite** [comment]
This is now fixed. I tried it with Callcentric and it seemed to work well. There still was a bit of delay, probably because of the callbacks going on between Verboice, Callcentric and my machine through ngrok, though in production that should be a bit faster, I guess.

As for Verboice, the logic to forward this `numDigits` parameter seems to be already implemented: https://github.com/instedd/verboice/search?utf8=%E2%9C%93&q=numDigits&type= (though when we deply this to staging it would be nice to test it against Twilio). The test should consider that after pressing the last digit for an answer, less than 5 seconds elapse, since that's the default timeout for Twilio.

**Comment by steesdale** [comment]
I also noticed that for the first IVR message played, there was between a 5-10 second lag.  Is this included in this fix.  For example... 

Phone rings;
User says hello? 
one second, 2, 3, 4, 5, 6, 7, 8, 9, 10 
Hi this is a survey from the MOH. 

I would expect the message from the MOH to start much faster.  
@waj thoughts?

**Comment by waj** [comment]
Maybe the audio file for the first message is too big. Can you share one of those files so we can test it locally?

**Comment by steesdale** [comment]
hi @waj, I emailed you the intro file for the prelude lag.  I wonder if this is a separate issue?  @nditada fyi...

**Comment by mmuller** [comment]
Working properly in version 0.9.0
